FROM jenkins/jenkins:lts

USER root

# Install Docker CLI inside the Jenkins image
RUN apt-get update && apt-get install -y docker.io && apt-get clean

# Allow the Jenkins user to access Docker socket
RUN usermod -aG docker jenkins

USER jenkins
